rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/', views.about, name='about'),
	url(r'^add_category/$', views.add_category, name= 'add_category'),
	url(r'^category/(?P<category_name_slug>[\w\-]+)add_page/$', views.add_page, name= 'add_page'),
	url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
	url(r'^register/$', views.register, name="register"),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^restricted/$', views.restricted, name='restricted'),
	url(r'^logout/$', views.user_logout, name='logout')
] 

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^rango/', include('rango.urls')),
	# above maps any URLs starting
	# with rango/ to be handled by
	# the rango application
	url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=128, unique=True)
	views = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)
	slug = models.SlugField(unique=True)
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)
		
	class Meta:
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name
		
class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=128)
	url = models.URLField()
	views = models.IntegerField(default=0)
	
	
	def __str__(self):
		return self.title

class UserProfile(models.Model):
	user = models.OneToOneField(User)

	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __str__(self):
		return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)


    # provide additional info on the form 
    class Meta:
        #link modelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please emter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

def index(request):

    request.session.set_test_cookie()

    category_list = Category.objects.order_by("-likes")[:5]
    page_list = Page.objects.order_by("-views")[:5]
    context_dict = {"categories":category_list, "pages":page_list}

    # handle cookies
    visitor_cookie_handler(request)
    context_dict["visits"] = request.session["visits"]

    response = render(request, "rango/index.html", context_dict)
    return response

def visitor_cookie_handler(request):
    # Get number of visits to the site by obtaining visits cookie (default 1)
    visits = int(get_server_side_cookie(request, "visits", "1"))

    last_visit_cookie = get_server_side_cookie(
        request, "last_visit", str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        "%Y-%m-%d %H:%M:%S")

    # checking for visits
    if (datetime.now() - last_visit_time).seconds > 10:
        visits += 1

        # update cookie
        request.session["last_visit"] = str(datetime.now())
    else:
        #visits = 1

        # set cookie
        request.session["last_visit"] = last_visit_cookie

    # update/set visits cookie
    request.session["visits"] = visits

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    visitor_cookie_handler(request)
    context_dict = {}
    context_dict["visits"] = request.session["visits"]

    return render(request, "rango/about.html", context_dict)

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict["pages"] = pages
        context_dict["category"] = category

    except Category.DoesNotExist:
        context_dict["pages"] = None
        context_dict["category"] = None

    return render(request, "rango/category.html", context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat = form.save(commit=True)
            print(cat, cat.slug)
            return index(request)
        else:
            print(form.errors)

    return render(request, "rango/add_category.html", {"form":form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                cat = page.save()
                print("Page %s has been added." % cat)
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {"form":form, "category":category}
    return render(request, "rango/add_page.html", context_dict)

def register(request):
    
    # tell template if registration was successful
    registered = False

    # if POST, process form data
    if request.method == "POST":
        # try to grab information from raw form
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # if both forms valid
        if user_form.is_valid() and profile_form.is_valid():
            # save to database
            user = user_form.save()

            # hash PW, update
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # if picture provided
            if "picture" in request.FILES:
                profile.picture = request.FILES["picture"]

            profile.save()
            registered = True
            
        else:
            print(user_form.errors, profile.form_errors)

        # if not POST, render blank form
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # render template depending on context
    return render(request,
                    "rango/register.html",
                    {"user_form":user_form,
                    "profile_form":profile_form,
                    "registered":registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        # if login details correct
        if user:
            # if account is active
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, "rango/login.html",  {})

@login_required
def restricted(request):
    return render(request, "rango/restricted.html", {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

templates/rango/about.html
{% extends 'rango/base.html' %}

{% block title_block %}
	About
{% endblock %}

{% block body_block %}
	<div>
			This tutorial has been put together by William Ainsworth.
			<strong>{{ boldmessage }}</strong><br />
			<p>visits: {{ visits }}</p>
	</div>

	<!-- Image -->
	<img src="{{ MEDIA_URL}}cat.jpg" alt ="Picture of cat" />

{% endblock %}
	
	

templates/rango/add_category.html
{% extends "rango/base.html" %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category'%}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category"/>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}

{% block title_block %}
    {{category.name}} - Add Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page</h1>
    <div>
        <form id="page_form" method="post" action="">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Page" />
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>

        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>

        <div>
            {% block body_block %}
            Default block
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                {% else %}
                    <li><a href="{% url 'rango:login' %}">Sign In</a></li>
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                 {% endif %}
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/category.html
{% extends "rango/base.html" %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
	    <h1> {{ category.name }} </h1>

	    {% if pages %}
		    <ul>
		    {% for page in pages %}
			    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
		    {% endfor %}
		    </ul>
	    {% else %}
		    <strong> No pages currently in category.</strong>
	    {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %}
	    The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li> <strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Home
{% endblock %}

{% block body_block %}

	<h1>Rango says...</h1
		<div> 
			{% if user.is_authenticated %}
				howdy {{ user.username }}!
			{% else %}
				hey there partner! 
			{% endif %}
		</div>
	<h2>Most Liked Categories</h2>

	<div>
	{% if categories %}
	<ul>
		{% for category in categories %}
			<li>
				<a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>There are no categories present.</strong>
	{% endif %}
	</div>
	<h2>Most Viewed Pages</h2>
	<div>
	
	{% if pages %}
	
	<ul>
		{% for page in pages %}
			
			<li><a href= "{{page.url}}">{{page.title}}</a></li>
			
		{% endfor %}
	</ul>
	{% else %}
		<strong>There are no categories present.</strong>
	{% endif %}
	</div>

	<div>
			<p>visits: {{ visits }}</p>
		<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
	</div>
{% endblock %}

templates/rango/login.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit"/>
    </form>
{% endblock %}

templates/rango/register.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1> About Page </h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url "rango:index" %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action=""
              enctype="multipart/form-data">

            {% csrf_token %}

            <!--Display-->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <!-- button to submit-->
            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock %}

{% block body_block %}
    Since your're logged in, you can see this text!
{% endblock %}